import type {
  CanvasModelRole,
  GatewayProviderKind,
  GatewayRequestKind,
  ModelMediaKind,
} from "@prisma/client";

import {
  MINIMAX_MUSIC_MODELS,
  MINIMAX_SPEECH_MODELS,
} from "@/lib/gateway/minimax-speech-models";
import {
  ELEVENLABS_SFX_MODELS,
  ELEVENLABS_STS_MODELS,
  ELEVENLABS_MUSIC_MODELS,
} from "@/lib/gateway/elevenlabs-models";
import {
  KIE_ELEVENLABS_TTS_MODEL_KEY,
  KIE_ELEVENLABS_V3_MODEL_KEY,
  KIE_SUNO_API_MODEL_KEY,
} from "@/lib/gateway/kie-audio-models";

type CanonicalModelDef = {
  canonicalModelKey: string;
  displayName: string;
  description?: string;
  mediaKind: ModelMediaKind;
  role: CanvasModelRole;
  requestKind: GatewayRequestKind;
  appTags: string[];
  sortOrder: number;
  routes: Array<{
    vendor: string;
    modelKey: string;
    providerKind: GatewayProviderKind;
  }>;
  primaryVendor: string;
  billingKind?: "PER_IMAGE" | "PER_SECOND" | "PER_1K_TOKENS" | "PER_CALL";
  unitLabel?: string;
};

/**
 * 历史/工具站直接提交的 vendor modelKey（未走 canonical 选模 UI）。
 * 注册表非空时须经 GatewayModelRoute，否则 createTask 500（同 aitryon 试衣问题）。
 */
const VISUAL = ["canvas", "story", "tool", "ecom"] as const;

function dashVideo(modelKey: string, sortOrder: number): CanonicalModelDef {
  return {
    canonicalModelKey: modelKey,
    displayName: modelKey,
    mediaKind: "IMAGE_TO_VIDEO",
    role: "VIDEO",
    requestKind: "VIDEO",
    appTags: [...VISUAL],
    sortOrder,
    primaryVendor: "aliyun",
    billingKind: "PER_SECOND",
    unitLabel: "元/秒",
    routes: [{ vendor: "aliyun", modelKey, providerKind: "DASHSCOPE" }],
  };
}

function bailianVideo(modelKey: string, sortOrder: number): CanonicalModelDef {
  return {
    canonicalModelKey: modelKey,
    displayName: modelKey,
    mediaKind: "VIDEO_TO_VIDEO",
    role: "VIDEO",
    requestKind: "VIDEO",
    appTags: [...VISUAL],
    sortOrder,
    primaryVendor: "aliyun",
    billingKind: "PER_SECOND",
    unitLabel: "元/秒",
    routes: [{ vendor: "aliyun", modelKey, providerKind: "BAILIAN" }],
  };
}

function kieImage(modelKey: string, sortOrder: number): CanonicalModelDef {
  return {
    canonicalModelKey: modelKey,
    displayName: modelKey,
    mediaKind: "TEXT_TO_IMAGE",
    role: "IMAGE",
    requestKind: "IMAGE",
    appTags: [...VISUAL],
    sortOrder,
    primaryVendor: "kie",
    billingKind: "PER_IMAGE",
    unitLabel: "元/张",
    routes: [{ vendor: "kie", modelKey, providerKind: "KIE" }],
  };
}

function kieVideo(modelKey: string, sortOrder: number): CanonicalModelDef {
  return {
    canonicalModelKey: modelKey,
    displayName: modelKey,
    mediaKind: "IMAGE_TO_VIDEO",
    role: "VIDEO",
    requestKind: "VIDEO",
    appTags: [...VISUAL],
    sortOrder,
    primaryVendor: "kie",
    billingKind: "PER_SECOND",
    unitLabel: "元/秒",
    routes: [{ vendor: "kie", modelKey, providerKind: "KIE" }],
  };
}

function kieV2v(modelKey: string, sortOrder: number): CanonicalModelDef {
  return {
    canonicalModelKey: modelKey,
    displayName: modelKey,
    mediaKind: "VIDEO_TO_VIDEO",
    role: "VIDEO",
    requestKind: "VIDEO",
    appTags: [...VISUAL],
    sortOrder,
    primaryVendor: "kie",
    billingKind: "PER_SECOND",
    unitLabel: "元/秒",
    routes: [{ vendor: "kie", modelKey, providerKind: "KIE" }],
  };
}

function kieMusic(
  canonicalModelKey: string,
  modelKey: string,
  displayName: string,
  description: string,
  sortOrder: number,
): CanonicalModelDef {
  return {
    canonicalModelKey,
    displayName,
    description,
    mediaKind: "TEXT_LLM",
    role: "LLM",
    requestKind: "MUSIC",
    appTags: ["canvas", "story", "tool"],
    sortOrder,
    primaryVendor: "kie",
    billingKind: "PER_CALL",
    unitLabel: "元/次",
    routes: [{ vendor: "kie", modelKey, providerKind: "KIE" }],
  };
}

function kieTts(
  canonicalModelKey: string,
  modelKey: string,
  displayName: string,
  description: string,
  sortOrder: number,
): CanonicalModelDef {
  return {
    canonicalModelKey,
    displayName,
    description,
    mediaKind: "TEXT_LLM",
    role: "LLM",
    requestKind: "TTS",
    appTags: ["canvas", "story", "tool"],
    sortOrder,
    primaryVendor: "kie",
    billingKind: "PER_CALL",
    unitLabel: "元/次",
    routes: [{ vendor: "kie", modelKey, providerKind: "KIE" }],
  };
}

function bailianChat(modelKey: string, sortOrder: number): CanonicalModelDef {
  return {
    canonicalModelKey: modelKey,
    displayName: modelKey,
    mediaKind: "TEXT_LLM",
    role: "LLM",
    requestKind: "CHAT",
    appTags: [...VISUAL, "prompt-optimizer"],
    sortOrder,
    primaryVendor: "aliyun",
    billingKind: "PER_1K_TOKENS",
    unitLabel: "元/百万 tokens",
    routes: [{ vendor: "aliyun", modelKey, providerKind: "BAILIAN" }],
  };
}

export const LEGACY_INVOKE_MODEL_REGISTRY: CanonicalModelDef[] = [
  {
    canonicalModelKey: "wanx2.1-t2i-plus",
    displayName: "万相文生图 Plus",
    mediaKind: "TEXT_TO_IMAGE",
    role: "IMAGE",
    requestKind: "IMAGE",
    appTags: ["tool"],
    sortOrder: 50,
    primaryVendor: "aliyun",
    billingKind: "PER_IMAGE",
    unitLabel: "元/张",
    routes: [{ vendor: "aliyun", modelKey: "wanx2.1-t2i-plus", providerKind: "DASHSCOPE" }],
  },
  {
    canonicalModelKey: "wanx2.1-t2i-turbo",
    displayName: "万相文生图 Turbo",
    mediaKind: "TEXT_TO_IMAGE",
    role: "IMAGE",
    requestKind: "IMAGE",
    appTags: ["tool", "ecom"],
    sortOrder: 51,
    primaryVendor: "aliyun",
    billingKind: "PER_IMAGE",
    unitLabel: "元/张",
    routes: [{ vendor: "aliyun", modelKey: "wanx2.1-t2i-turbo", providerKind: "DASHSCOPE" }],
  },
  {
    canonicalModelKey: "qwen3-tts-flash",
    displayName: "通义 TTS Flash",
    mediaKind: "TEXT_LLM",
    role: "LLM",
    requestKind: "TTS",
    appTags: ["canvas", "story"],
    sortOrder: 52,
    primaryVendor: "aliyun",
    routes: [{ vendor: "aliyun", modelKey: "qwen3-tts-flash", providerKind: "BAILIAN" }],
  },
  {
    canonicalModelKey: "qwen3-tts",
    displayName: "通义 TTS",
    mediaKind: "TEXT_LLM",
    role: "LLM",
    requestKind: "TTS",
    appTags: ["canvas", "story"],
    sortOrder: 53,
    primaryVendor: "aliyun",
    routes: [{ vendor: "aliyun", modelKey: "qwen3-tts", providerKind: "BAILIAN" }],
  },
  dashVideo("happyhorse-1.0-i2v", 54),
  dashVideo("happyhorse-1.0-t2v", 55),
  dashVideo("happyhorse-1.0-video-edit", 56),
  dashVideo("wan2.6-i2v", 57),
  dashVideo("wan2.6-t2v", 58),
  dashVideo("wan2.6-i2v-flash", 59),
  bailianVideo("wan2.6-r2v-flash", 60),
  dashVideo("wan2.7-i2v-2026-04-25", 61),
  dashVideo("wan2.7-t2v", 62),
  dashVideo("wan2.7-t2v-2026-04-25", 63),
  dashVideo("wan2.5-i2v-preview", 64),
  dashVideo("wan2.5-t2v-preview", 65),
  dashVideo("pixverse-c1-it2v", 66),
  dashVideo("pixverse-c1-t2v", 67),
  dashVideo("pixverse-v6-it2v", 68),
  dashVideo("pixverse-v6-t2v", 69),
  kieImage("flux-2-pro", 70),
  {
    canonicalModelKey: "gpt-image-1",
    displayName: "GPT Image 1.5 (KIE)",
    mediaKind: "TEXT_TO_IMAGE",
    role: "IMAGE",
    requestKind: "IMAGE",
    appTags: [...VISUAL],
    sortOrder: 71,
    primaryVendor: "kie",
    billingKind: "PER_IMAGE",
    unitLabel: "元/张",
    routes: [{ vendor: "kie", modelKey: "gpt-image-1", providerKind: "KIE" }],
  },
  {
    canonicalModelKey: "gpt-image-2",
    displayName: "GPT Image 2 (KIE)",
    mediaKind: "TEXT_TO_IMAGE",
    role: "IMAGE",
    requestKind: "IMAGE",
    appTags: [...VISUAL],
    sortOrder: 72,
    primaryVendor: "kie",
    billingKind: "PER_IMAGE",
    unitLabel: "元/张",
    routes: [
      { vendor: "kie", modelKey: "gpt-image-2", providerKind: "KIE" },
      { vendor: "kie", modelKey: "gpt-image-2-text-to-image", providerKind: "KIE" },
      { vendor: "kie", modelKey: "gpt-image-2-image-to-image", providerKind: "KIE" },
    ],
  },
  kieImage("seedream-4.5", 73),
  kieImage("seedream-5-lite", 74),
  {
    canonicalModelKey: "google-nano-banana",
    displayName: "NanoBanana Gemini 2.5 Flash · 文生图",
    description: "KIE · google/nano-banana 文生图",
    mediaKind: "TEXT_TO_IMAGE",
    role: "IMAGE",
    requestKind: "IMAGE",
    appTags: [...VISUAL],
    sortOrder: 74.5,
    primaryVendor: "kie",
    billingKind: "PER_IMAGE",
    unitLabel: "元/张",
    routes: [{ vendor: "kie", modelKey: "google/nano-banana", providerKind: "KIE" }],
  },
  {
    canonicalModelKey: "google-nano-banana-i2i",
    displayName: "NanoBanana Gemini 2.5 Flash · 图生图",
    description: "KIE · google/nano-banana-edit 图生图 / 编辑",
    mediaKind: "TEXT_TO_IMAGE",
    role: "IMAGE",
    requestKind: "IMAGE",
    appTags: [...VISUAL],
    sortOrder: 74.55,
    primaryVendor: "kie",
    billingKind: "PER_IMAGE",
    unitLabel: "元/张",
    routes: [{ vendor: "kie", modelKey: "google/nano-banana-edit", providerKind: "KIE" }],
  },
  kieImage("nano-banana-2", 74.6),
  {
    canonicalModelKey: "kie-4o-image",
    displayName: "4o Image · 文/图生图",
    description: "KIE · 4o-image API · 文生图 / 参考图编辑",
    mediaKind: "TEXT_TO_IMAGE",
    role: "IMAGE",
    requestKind: "IMAGE",
    appTags: [...VISUAL],
    sortOrder: 74.7,
    primaryVendor: "kie",
    billingKind: "PER_IMAGE",
    unitLabel: "元/张",
    routes: [{ vendor: "kie", modelKey: "4o-image", providerKind: "KIE" }],
  },
  kieImage("qwen-text-to-image", 75),
  {
    canonicalModelKey: "grok-imagine/text-to-image",
    displayName: "Grok Imagine · 文生图",
    mediaKind: "TEXT_TO_IMAGE",
    role: "IMAGE",
    requestKind: "IMAGE",
    appTags: [...VISUAL],
    sortOrder: 87,
    primaryVendor: "kie",
    billingKind: "PER_IMAGE",
    unitLabel: "元/张",
    routes: [{ vendor: "kie", modelKey: "grok-imagine/text-to-image", providerKind: "KIE" }],
  },
  {
    canonicalModelKey: "grok-imagine/image-to-video",
    displayName: "Grok Imagine · 图生视频",
    mediaKind: "IMAGE_TO_VIDEO",
    role: "VIDEO",
    requestKind: "VIDEO",
    appTags: [...VISUAL],
    sortOrder: 88,
    primaryVendor: "kie",
    billingKind: "PER_SECOND",
    unitLabel: "元/秒",
    routes: [{ vendor: "kie", modelKey: "grok-imagine/image-to-video", providerKind: "KIE" }],
  },
  {
    canonicalModelKey: "grok-imagine-video-1-5-preview",
    displayName: "Grok Imagine Video 1.5",
    mediaKind: "IMAGE_TO_VIDEO",
    role: "VIDEO",
    requestKind: "VIDEO",
    appTags: [...VISUAL],
    sortOrder: 89,
    primaryVendor: "kie",
    billingKind: "PER_SECOND",
    unitLabel: "元/秒",
    routes: [
      { vendor: "kie", modelKey: "grok-imagine-video-1-5-preview", providerKind: "KIE" },
    ],
  },
  kieV2v("wan/2-6-video-to-video", 90),
  kieV2v("kling-2.6/motion-control", 91),
  kieV2v("kling-3.0/motion-control", 92),
  {
    canonicalModelKey: "topaz-labs/video-enhance",
    displayName: "Topaz Labs · 高清视频增强",
    mediaKind: "VIDEO_TO_VIDEO",
    role: "VIDEO",
    requestKind: "VIDEO",
    appTags: [...VISUAL],
    sortOrder: 92.5,
    primaryVendor: "topaz",
    billingKind: "PER_SECOND",
    unitLabel: "元/次",
    routes: [
      {
        vendor: "topaz",
        modelKey: "topaz-labs/video-enhance",
        providerKind: "TOPAZ" as const,
      },
    ],
  },
  {
    canonicalModelKey: "topaz/video-upscale",
    displayName: "Topaz Video Upscale (KIE)",
    mediaKind: "VIDEO_TO_VIDEO",
    role: "VIDEO",
    requestKind: "VIDEO",
    appTags: [...VISUAL],
    sortOrder: 93,
    primaryVendor: "kie",
    billingKind: "PER_SECOND",
    unitLabel: "元/次",
    routes: [{ vendor: "kie", modelKey: "topaz/video-upscale", providerKind: "KIE" }],
  },
  {
    canonicalModelKey: "kie-seedance-2.0",
    displayName: "Seedance 2.0 (KIE)",
    description: "KIE · bytedance/seedance-2 · 图/视频/音频多参考生视频",
    mediaKind: "IMAGE_TO_VIDEO",
    role: "VIDEO",
    requestKind: "VIDEO",
    appTags: [...VISUAL],
    sortOrder: 75.8,
    primaryVendor: "kie",
    billingKind: "PER_SECOND",
    unitLabel: "元/秒",
    routes: [{ vendor: "kie", modelKey: "bytedance/seedance-2", providerKind: "KIE" }],
  },
  kieVideo("veo-2", 76),
  {
    canonicalModelKey: "veo-3",
    displayName: "Google Veo 3",
    mediaKind: "IMAGE_TO_VIDEO",
    role: "VIDEO",
    requestKind: "VIDEO",
    appTags: [...VISUAL],
    sortOrder: 76.1,
    primaryVendor: "kie",
    billingKind: "PER_SECOND",
    unitLabel: "元/秒",
    routes: [{ vendor: "kie", modelKey: "veo3", providerKind: "KIE" }],
  },
  {
    canonicalModelKey: "veo-3.1",
    displayName: "Google Veo 3.1",
    mediaKind: "IMAGE_TO_VIDEO",
    role: "VIDEO",
    requestKind: "VIDEO",
    appTags: [...VISUAL],
    sortOrder: 76.2,
    primaryVendor: "kie",
    billingKind: "PER_SECOND",
    unitLabel: "元/秒",
    routes: [{ vendor: "kie", modelKey: "veo3.1", providerKind: "KIE" }],
  },
  {
    canonicalModelKey: "seedance-2.0-mini",
    displayName: "Seedance 2.0 Mini",
    description: "KIE · bytedance/seedance-2-mini · 图/文生视频",
    mediaKind: "IMAGE_TO_VIDEO",
    role: "VIDEO",
    requestKind: "VIDEO",
    appTags: [...VISUAL],
    sortOrder: 76.3,
    primaryVendor: "kie",
    billingKind: "PER_SECOND",
    unitLabel: "元/秒",
    routes: [{ vendor: "kie", modelKey: "bytedance/seedance-2-mini", providerKind: "KIE" }],
  },
  {
    canonicalModelKey: "hailuo-2.3-i2v",
    displayName: "海螺 2.3 图生视频",
    mediaKind: "IMAGE_TO_VIDEO",
    role: "VIDEO",
    requestKind: "VIDEO",
    appTags: [...VISUAL],
    sortOrder: 76.4,
    primaryVendor: "kie",
    billingKind: "PER_SECOND",
    unitLabel: "元/秒",
    routes: [
      { vendor: "kie", modelKey: "hailuo/2-3-image-to-video-standard", providerKind: "KIE" },
      { vendor: "kie", modelKey: "hailuo/2-3-image-to-video-pro", providerKind: "KIE" },
    ],
  },
  {
    canonicalModelKey: "kling-2.5-turbo-i2v",
    displayName: "可灵 2.5 Turbo 图生视频",
    mediaKind: "IMAGE_TO_VIDEO",
    role: "VIDEO",
    requestKind: "VIDEO",
    appTags: [...VISUAL],
    sortOrder: 76.5,
    primaryVendor: "kie",
    billingKind: "PER_SECOND",
    unitLabel: "元/秒",
    routes: [
      { vendor: "kie", modelKey: "kling/v2-5-turbo-image-to-video-pro", providerKind: "KIE" },
      { vendor: "kie", modelKey: "kling/v2-5-turbo-text-to-video-pro", providerKind: "KIE" },
    ],
  },
  {
    canonicalModelKey: "claude-opus-4-8",
    displayName: "Claude Opus 4.8",
    mediaKind: "TEXT_LLM",
    role: "LLM",
    requestKind: "CHAT",
    appTags: [...VISUAL, "prompt-optimizer"],
    sortOrder: 77.1,
    primaryVendor: "kie",
    billingKind: "PER_1K_TOKENS",
    unitLabel: "元/百万 tokens",
    routes: [{ vendor: "kie", modelKey: "claude-opus-4-8", providerKind: "KIE" }],
  },
  {
    canonicalModelKey: "claude-opus-4-5",
    displayName: "Claude Opus 4.5",
    mediaKind: "TEXT_LLM",
    role: "LLM",
    requestKind: "CHAT",
    appTags: [...VISUAL, "prompt-optimizer"],
    sortOrder: 77.2,
    primaryVendor: "kie",
    billingKind: "PER_1K_TOKENS",
    unitLabel: "元/百万 tokens",
    routes: [{ vendor: "kie", modelKey: "claude-opus-4-5", providerKind: "KIE" }],
  },
  {
    canonicalModelKey: "gemini-3-5-flash",
    displayName: "Gemini 3.5 Flash",
    mediaKind: "TEXT_LLM",
    role: "LLM",
    requestKind: "CHAT",
    appTags: [...VISUAL, "prompt-optimizer"],
    sortOrder: 77.3,
    primaryVendor: "kie",
    billingKind: "PER_1K_TOKENS",
    unitLabel: "元/百万 tokens",
    routes: [{ vendor: "kie", modelKey: "gemini-3-5-flash", providerKind: "KIE" }],
  },
  {
    canonicalModelKey: "gemini-3-pro",
    displayName: "Gemini 3 Pro",
    mediaKind: "TEXT_LLM",
    role: "LLM",
    requestKind: "CHAT",
    appTags: [...VISUAL, "prompt-optimizer"],
    sortOrder: 77.4,
    primaryVendor: "kie",
    billingKind: "PER_1K_TOKENS",
    unitLabel: "元/百万 tokens",
    routes: [{ vendor: "kie", modelKey: "gemini-3-pro", providerKind: "KIE" }],
  },
  bailianChat("qwen-vl-max", 78),
  bailianChat("qwen-vl-plus", 78),
  bailianChat("qwen3-vl-plus", 79),
  bailianChat("qwen3-vl-flash", 80),
  bailianChat("qwen3.5-plus", 81),
  bailianChat("qwen3.5-27b", 82),
  bailianChat("qwen3.6-plus", 83),
  bailianChat("qwen3.6-flash", 84),
  kieMusic(
    "kie-suno-api",
    KIE_SUNO_API_MODEL_KEY,
    "Suno API",
    "KIE · Suno 文生音乐 · V5 系列",
    72.5,
  ),
  kieTts(
    "kie-elevenlabs-v3",
    KIE_ELEVENLABS_V3_MODEL_KEY,
    "ElevenLabs V3",
    "KIE · ElevenLabs 多语言对白 · 情感表达",
    72.6,
  ),
  kieTts(
    "kie-elevenlabs-tts",
    KIE_ELEVENLABS_TTS_MODEL_KEY,
    "ElevenLabs Text to Speech",
    "KIE · ElevenLabs 多语言 TTS",
    72.7,
  ),
  {
    canonicalModelKey: "hunyuan-3d-express",
    displayName: "混元 3D Express",
    mediaKind: "TEXT_TO_IMAGE",
    role: "IMAGE",
    requestKind: "IMAGE",
    appTags: ["canvas"],
    sortOrder: 85,
    primaryVendor: "tencent",
    routes: [{ vendor: "tencent", modelKey: "hunyuan-3d-express", providerKind: "HUNYUAN" }],
  },
  {
    canonicalModelKey: "hy-3d-express",
    displayName: "混元 3D Express（别名）",
    mediaKind: "TEXT_TO_IMAGE",
    role: "IMAGE",
    requestKind: "IMAGE",
    appTags: ["canvas"],
    sortOrder: 86,
    primaryVendor: "tencent",
    routes: [{ vendor: "tencent", modelKey: "hy-3d-express", providerKind: "HUNYUAN" }],
  },
  ...MINIMAX_SPEECH_MODELS.map((m, i) => ({
    canonicalModelKey: m.modelKey,
    displayName: m.label,
    description: m.subtitle,
    mediaKind: "TEXT_LLM" as const,
    role: "LLM" as const,
    requestKind: "TTS" as const,
    appTags: ["tool", "canvas", "story"],
    sortOrder: 100 + i,
    primaryVendor: "minimax",
    billingKind: "PER_CALL" as const,
    unitLabel: "元/次",
    routes: [{ vendor: "minimax", modelKey: m.modelKey, providerKind: "MINIMAX" as const }],
  })),
  ...MINIMAX_MUSIC_MODELS.map((m, i) => ({
    canonicalModelKey: m.modelKey,
    displayName: m.label,
    description: m.subtitle,
    mediaKind: "TEXT_LLM" as const,
    role: "LLM" as const,
    requestKind: "MUSIC" as const,
    appTags: ["tool"],
    sortOrder: 110 + i,
    primaryVendor: "minimax",
    billingKind: "PER_CALL" as const,
    unitLabel: "元/次",
    routes: [{ vendor: "minimax", modelKey: m.modelKey, providerKind: "MINIMAX" as const }],
  })),
  ...ELEVENLABS_STS_MODELS.map((m, i) => ({
    canonicalModelKey: m.modelKey,
    displayName: m.label,
    description: m.subtitle,
    mediaKind: "TEXT_LLM" as const,
    role: "LLM" as const,
    requestKind: "TTS" as const,
    appTags: ["tool"],
    sortOrder: 120 + i,
    primaryVendor: "elevenlabs",
    billingKind: "PER_CALL" as const,
    unitLabel: "元/次",
    routes: [{ vendor: "elevenlabs", modelKey: m.modelKey, providerKind: "ELEVENLABS" as const }],
  })),
  ...ELEVENLABS_SFX_MODELS.map((m, i) => ({
    canonicalModelKey: m.modelKey,
    displayName: m.label,
    description: m.subtitle,
    mediaKind: "TEXT_LLM" as const,
    role: "LLM" as const,
    requestKind: "OTHER" as const,
    appTags: ["tool"],
    sortOrder: 125 + i,
    primaryVendor: "elevenlabs",
    billingKind: "PER_CALL" as const,
    unitLabel: "元/次",
    routes: [{ vendor: "elevenlabs", modelKey: m.modelKey, providerKind: "ELEVENLABS" as const }],
  })),
  ...ELEVENLABS_MUSIC_MODELS.map((m, i) => ({
    canonicalModelKey: m.modelKey,
    displayName: m.label,
    description: m.subtitle,
    mediaKind: "TEXT_LLM" as const,
    role: "LLM" as const,
    requestKind: "MUSIC" as const,
    appTags: ["tool"],
    sortOrder: 128 + i,
    primaryVendor: "elevenlabs",
    billingKind: "PER_CALL" as const,
    unitLabel: "元/次",
    routes: [{ vendor: "elevenlabs", modelKey: m.modelKey, providerKind: "ELEVENLABS" as const }],
  })),
];
