/** 平台目录（V1 可选，其余展示为即将支持） */
window.PUBLISHER_PLATFORM_CATALOG = [
  {
    id: "weibo",
    label: "微博",
    en: "weibo",
    category: "common",
    contentTypes: ["dynamic", "video", "article"],
    color: "#e6162d",
    v1: true,
  },
  {
    id: "xiaohongshu",
    label: "小红书",
    en: "rednote",
    category: "common",
    contentTypes: ["dynamic", "video"],
    color: "#fe2c55",
    v1: true,
  },
  {
    id: "douyin",
    label: "抖音",
    en: "douyin",
    category: "common",
    contentTypes: ["dynamic", "video"],
    color: "#010101",
    v1: true,
  },
  {
    id: "bilibili",
    label: "B站",
    en: "bilibili",
    category: "common",
    contentTypes: ["dynamic", "video", "article"],
    color: "#fb7299",
    v1: true,
  },
  {
    id: "wechat_mp",
    label: "微信公众号",
    en: "weixin",
    category: "common",
    contentTypes: ["dynamic", "article"],
    color: "#07c160",
    v1: true,
    semiAuto: true,
  },
  {
    id: "x",
    label: "X",
    en: "x",
    category: "common",
    contentTypes: ["dynamic", "article"],
    color: "#000000",
    v1: false,
  },
  {
    id: "zhihu",
    label: "知乎",
    en: "zhihu",
    category: "common",
    contentTypes: ["dynamic", "video", "article"],
    color: "#0066ff",
    v1: false,
  },
  {
    id: "xueqiu",
    label: "雪球",
    en: "xueqiu",
    category: "domestic",
    contentTypes: ["dynamic", "article"],
    color: "#0077cc",
    v1: false,
  },
  {
    id: "okjike",
    label: "即刻",
    en: "okjike",
    category: "domestic",
    contentTypes: ["dynamic", "video"],
    color: "#ffe411",
    v1: false,
  },
  {
    id: "kuaishou",
    label: "快手",
    en: "kuaishou",
    category: "domestic",
    contentTypes: ["dynamic", "video"],
    color: "#ff4906",
    v1: false,
  },
  {
    id: "baijiahao",
    label: "百家号",
    en: "baijiahao",
    category: "domestic",
    contentTypes: ["dynamic", "video", "article"],
    color: "#2932e1",
    v1: false,
  },
  {
    id: "toutiao",
    label: "头条",
    en: "toutiao",
    category: "domestic",
    contentTypes: ["dynamic", "video", "article"],
    color: "#ff0000",
    v1: false,
  },
];

window.CONTENT_TYPE_LABELS = {
  dynamic: "动态",
  video: "视频",
  article: "文章",
  podcast: "播客",
};

window.getPlatformById = function getPlatformById(id) {
  return window.PUBLISHER_PLATFORM_CATALOG.find((p) => p.id === id);
};
