/** 百炼 · 图像擦除补全（见阿里云 image-erasure-and-completion 文档） */
export const IMAGE_ERASE_COMPLETION_MODEL = "image-erase-completion";

/** 百炼 · 图像画面扩展 */
export const IMAGE_OUTPAINT_MODEL = "image-out-painting";

/** 扩图 API 默认参数 · add_watermark 默认 true 会烧左下角 "Generated by AI" */
export const OUTPAINT_API_BASE_PARAMETERS = {
  add_watermark: false,
  limit_image_size: true,
} as const;
