/**
 * Pro2 节点默认宽高（纯常量 · 无 libtv-dock-scale 依赖）
 * 供 types.ts / libtv-media-node-size 等避免与 story-pro2-node-chrome 循环引用。
 */

import {
  LIBTV_MEDIA_STAGE_LANDSCAPE_16_9_HEIGHT,
  LIBTV_MEDIA_STAGE_LANDSCAPE_WIDTH,
  LIBTV_MEDIA_STAGE_PORTRAIT_HEIGHT,
  LIBTV_SQUARE_IMAGE_NODE_HEIGHT,
  LIBTV_SQUARE_IMAGE_NODE_MIN_HEIGHT,
  LIBTV_SQUARE_IMAGE_NODE_MIN_WIDTH,
  LIBTV_SQUARE_IMAGE_NODE_WIDTH,
  LIBTV_AUDIO_TRACK_NODE_HEIGHT,
  LIBTV_AUDIO_TRACK_NODE_MIN_HEIGHT,
  LIBTV_AUDIO_TRACK_NODE_MIN_WIDTH,
  LIBTV_AUDIO_TRACK_NODE_WIDTH,
  LIBTV_AUDIO_MINI_PLAYER_HEIGHT,
} from "./libtv-node-chrome";
import {
  STYLE_LIBRARY_PREVIEW_ASPECT_H,
  STYLE_LIBRARY_PREVIEW_ASPECT_W,
} from "./style-library-card-chrome";

/** 控制类薄卡（列摘要等） */
export const PRO2_CONTROL_CARD_WIDTH = 360;
export const PRO2_CONTROL_CARD_HEIGHT = 140;

/** 2.0 · 3D 导演台控制卡（图 1） */
export const PRO2_3D_DESK_NODE_WIDTH = 360;
export const PRO2_3D_DESK_NODE_HEIGHT = 280;
export const PRO2_3D_DESK_NODE_MIN_WIDTH = 300;
export const PRO2_3D_DESK_NODE_MIN_HEIGHT = 240;

/** 2.0 标签节点 · 可压成单行便签 */
export const PRO2_TAG_NODE_MIN_WIDTH = 120;
export const PRO2_TAG_NODE_MIN_HEIGHT = 54;
export const PRO2_TAG_NODE_WIDTH = 440;
export const PRO2_TAG_NODE_HEIGHT = 88;

/** 2.0 文本节点（LibTV 卡片 · 默认 4:3 · 可拉伸） */
export const PRO2_TEXT_NODE_WIDTH = 440;
export const PRO2_TEXT_NODE_MIN_WIDTH = 320;
export const PRO2_TEXT_NODE_CARD_HEIGHT = Math.round((PRO2_TEXT_NODE_WIDTH * 3) / 4);
export const PRO2_TEXT_NODE_MIN_HEIGHT =
  Math.round((PRO2_TEXT_NODE_MIN_WIDTH * 3) / 4) + 28;
export const PRO2_TEXT_NODE_HEIGHT = PRO2_TEXT_NODE_CARD_HEIGHT + 28;

/** 2.0 故事剧本生成 / 脚本表格节点 */
export const PRO2_SCRIPT_NODE_WIDTH = 728;
export const PRO2_SCRIPT_NODE_MIN_WIDTH = 320;
export const PRO2_SCRIPT_NODE_CARD_HEIGHT = 367;
export const PRO2_SCRIPT_NODE_MIN_HEIGHT = 220;
export const PRO2_SCRIPT_NODE_HEIGHT = PRO2_SCRIPT_NODE_CARD_HEIGHT + 28;

/** 2.0 图片 / 风格素材节点 */
export const PRO2_IMAGE_NODE_WIDTH = LIBTV_SQUARE_IMAGE_NODE_WIDTH;
export const PRO2_IMAGE_NODE_HEIGHT = LIBTV_SQUARE_IMAGE_NODE_HEIGHT;
export const PRO2_IMAGE_NODE_MIN_WIDTH = LIBTV_SQUARE_IMAGE_NODE_MIN_WIDTH;
export const PRO2_IMAGE_NODE_MIN_HEIGHT = LIBTV_SQUARE_IMAGE_NODE_MIN_HEIGHT;
export const PRO2_IMAGE_NODE_CARD_HEIGHT = PRO2_IMAGE_NODE_HEIGHT;

/** 2.0 音频节点 */
export const PRO2_AUDIO_NODE_CARD_HEIGHT = LIBTV_AUDIO_MINI_PLAYER_HEIGHT;
export const PRO2_AUDIO_NODE_WIDTH = LIBTV_AUDIO_TRACK_NODE_WIDTH;
export const PRO2_AUDIO_NODE_HEIGHT = LIBTV_AUDIO_TRACK_NODE_HEIGHT;
export const PRO2_AUDIO_NODE_MIN_WIDTH = LIBTV_AUDIO_TRACK_NODE_MIN_WIDTH;
export const PRO2_AUDIO_NODE_MIN_HEIGHT = LIBTV_AUDIO_TRACK_NODE_MIN_HEIGHT;

/** 2.0 三视图角色节点 */
export const PRO2_CHARACTER_THREE_VIEW_WIDTH = 400;
export const PRO2_CHARACTER_THREE_VIEW_HEIGHT = 280;
export const PRO2_CHARACTER_THREE_VIEW_MIN_WIDTH = 320;
export const PRO2_CHARACTER_THREE_VIEW_MIN_HEIGHT = 160;
export const PRO2_CHARACTER_THREE_VIEW_CARD_HEIGHT = 252;

/** Pro2 媒体节点 · 外置标题行占用 */
export const PRO2_EXTERNAL_MEDIA_TITLE_CHROME_HEIGHT = 32;

/** 空态图片节点 · 默认 16:9 */
export const PRO2_IMAGE_NODE_16_9_WIDTH = LIBTV_MEDIA_STAGE_LANDSCAPE_WIDTH;
export const PRO2_IMAGE_NODE_16_9_HEIGHT =
  PRO2_EXTERNAL_MEDIA_TITLE_CHROME_HEIGHT +
  LIBTV_MEDIA_STAGE_LANDSCAPE_16_9_HEIGHT;

/** 风格素材节点 · 与风格库预览 400×550 竖版一致（算法对齐 libtv portrait preset） */
const PRO2_STYLE_ASSET_PORTRAIT_STAGE_H = LIBTV_MEDIA_STAGE_PORTRAIT_HEIGHT;
export const PRO2_STYLE_ASSET_NODE_WIDTH = Math.ceil(
  PRO2_STYLE_ASSET_PORTRAIT_STAGE_H *
    (STYLE_LIBRARY_PREVIEW_ASPECT_W / STYLE_LIBRARY_PREVIEW_ASPECT_H),
);
export const PRO2_STYLE_ASSET_NODE_HEIGHT =
  PRO2_EXTERNAL_MEDIA_TITLE_CHROME_HEIGHT + PRO2_STYLE_ASSET_PORTRAIT_STAGE_H;

/** 2.0 分镜图板节点 */
export const PRO2_FRAME_BOARD_WIDTH = 520;
export const PRO2_FRAME_BOARD_HEIGHT = 480;
export const PRO2_FRAME_BOARD_MIN_WIDTH = 400;
export const PRO2_FRAME_BOARD_MIN_HEIGHT = 320;

/** 列摘要薄卡 */
export const PRO2_COLUMN_CARD_WIDTH = 320;
export const PRO2_COLUMN_CARD_HEIGHT = 120;
