import { describe, expect, it } from "vitest";

import { buildEraseCompletionParameters } from "@/lib/canvas-image-edit/constants";

describe("buildEraseCompletionParameters", () => {
  it("disables vendor Generated by AI watermark by default", () => {
    const params = buildEraseCompletionParameters();
    expect(params.add_watermark).toBe(false);
    expect(params.fast_mode).toBe(true);
    expect(params.dilate_flag).toBe(true);
  });

  it("keeps watermark off when fast mode is disabled", () => {
    const params = buildEraseCompletionParameters({ fastMode: false });
    expect(params.add_watermark).toBe(false);
    expect(params.fast_mode).toBe(false);
  });
});
