import { describe, expect, it } from "vitest";
import { buildOutpaintParametersFromOffsets } from "@/lib/canvas-image-edit/run-canvas-image-outpaint";

describe("buildOutpaintParametersFromOffsets", () => {
  it("disables vendor Generated by AI watermark by default", () => {
    const params = buildOutpaintParametersFromOffsets({
      left_offset: 0,
      right_offset: 120,
      top_offset: 0,
      bottom_offset: 0,
    });
    expect(params.add_watermark).toBe(false);
    expect(params.right_offset).toBe(120);
  });
});
