/**
 * 平台内置风格库（真源由 docs/style.html 生成，预览图 URL 由 upload-style-library-images 脚本写入）
 */
export type StyleLibraryPreset = {
  id: string;
  category: string;
  name: string;
  prompt: string;
  imageUrl: string;
};

export const STYLE_LIBRARY_CATEGORIES = [
  "摄影写真",
  "电商营销",
  "动漫游戏",
  "风格插画",
  "平面设计",
  "建筑及室内设计",
  "创意玩法",
  "文创周边",
  "小说推文"
] as const;

export type StyleLibraryCategory = (typeof STYLE_LIBRARY_CATEGORIES)[number];

export const STYLE_LIBRARY_PRESETS: StyleLibraryPreset[] = [
  { id: "photo-e697a5e7b3bb", category: "摄影写真", name: "日系清新人像", prompt: "日系清新、自然光、柔和肤色、浅色系、干净背景、文艺氛围、高曝光质感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e697a5e7b3bb.webp" },
  { id: "photo-e6b8afe9a38e", category: "摄影写真", name: "港风复古写真", prompt: "港风、复古滤镜、胶片颗粒、暗调、暖黄灯光、氛围感、80年代", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e6b8afe9a38e.webp" },
  { id: "photo-e6b395e5bc8f", category: "摄影写真", name: "法式温柔人像", prompt: "法式、温柔、复古、蕾丝、柔光、浅景深、优雅姿态、暖调", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e6b395e5bc8f.webp" },
  { id: "photo-e69a97e8b083", category: "摄影写真", name: "暗调情绪写真", prompt: "暗调、情绪、光影对比、低饱和、故事感、高级灰、艺术氛围", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e69a97e8b083.webp" },
  { id: "photo-e6a3aee7b3bb", category: "摄影写真", name: "森系治愈写真", prompt: "森系、森林、绿植、逆光、清新、治愈、柔和、自然光影", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e6a3aee7b3bb.webp" },
  { id: "photo-e69d82e5bf97", category: "摄影写真", name: "杂志高级感写真", prompt: "杂志风、高级感、冷调、简洁背景、质感皮肤、时尚构图", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e69d82e5bf97.webp" },
  { id: "photo-e883b6e78987", category: "摄影写真", name: "胶片复古写真", prompt: "胶片、复古、颗粒感、褪色、暖调、文艺、怀旧感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e883b6e78987.webp" },
  { id: "photo-e6b885e696b0", category: "摄影写真", name: "清新校园写真", prompt: "校园、青春、清新、明亮、校服、阳光、干净、少年感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e6b885e696b0.webp" },
  { id: "photo-e58fa4e9a38e", category: "摄影写真", name: "古风汉服写真", prompt: "汉服、古风、古典、园林、柔光、温婉、传统服饰、意境", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e58fa4e9a38e.webp" },
  { id: "photo-e5a49ce699af", category: "摄影写真", name: "夜景氛围写真", prompt: "夜景、城市灯光、光斑、氛围感、暗调、情绪、街拍", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e5a49ce699af.webp" },
  { id: "photo-e6b885e696b0-2", category: "摄影写真", name: "清新海边写真", prompt: "海边、清新、蓝天、沙滩、逆光、治愈、夏日感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e6b885e696b0-2.webp" },
  { id: "photo-e5b7a5e7ac94", category: "摄影写真", name: "工笔写意人像", prompt: "工笔画、写意、国风、柔和、古典、素雅、意境风", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e5b7a5e7ac94.webp" },
  { id: "photo-e9ab98e5ae9a", category: "摄影写真", name: "高定时尚写真", prompt: "高定、时尚、大牌、冷调、高级感、精致妆容、杂志大片", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e9ab98e5ae9a.webp" },
  { id: "photo-e6b8a9e69f94", category: "摄影写真", name: "温柔光影写真", prompt: "光影、温柔、侧光、柔和、治愈、干净、简约背景", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e6b8a9e69f94.webp" },
  { id: "photo-e7baaae5ae9e", category: "摄影写真", name: "纪实风生活写真", prompt: "纪实、生活感、自然、抓拍、清新、日常、真实情绪", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/photo-e7baaae5ae9e.webp" },
  { id: "ecom-e7be8ee5a686", category: "电商营销", name: "美妆产品主图", prompt: "高清产品、干净背景、明亮打光、质感、精致、高对比、商业主图", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e7be8ee5a686.webp" },
  { id: "ecom-e69c8de8a385", category: "电商营销", name: "服装详情展示", prompt: "服装展示、干净背景、版型清晰、明亮、简约、商业质感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e69c8de8a385.webp" },
  { id: "ecom-e7be8ee9a39f", category: "电商营销", name: "美食带货海报", prompt: "美食、高清、诱人、暖调、食欲感、细节清晰、带货风格", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e7be8ee9a39f.webp" },
  { id: "ecom-e695b0e7a081", category: "电商营销", name: "数码产品主图", prompt: "数码产品、科技感、冷调、高清、简洁背景、高级质感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e695b0e7a081.webp" },
  { id: "ecom-e5aeb6e5b185", category: "电商营销", name: "家居好物展示", prompt: "家居、温馨、明亮、简约、质感、生活化、干净场景", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e5aeb6e5b185.webp" },
  { id: "ecom-e59bbde6bdae", category: "电商营销", name: "国潮风电商海报", prompt: "国潮、中国风、红色、喜庆、传统元素、商业海报", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e59bbde6bdae.webp" },
  { id: "ecom-e6b885e696b0", category: "电商营销", name: "清新风美妆场景", prompt: "清新、明亮、浅色系、美妆、柔和、干净、少女感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e6b885e696b0.webp" },
  { id: "ecom-e8bdbbe5a5a2", category: "电商营销", name: "轻奢风饰品展示", prompt: "轻奢、高级、质感、冷调、精致、简约背景、珠宝展示", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e8bdbbe5a5a2.webp" },
  { id: "ecom-e6af8de5a9b4", category: "电商营销", name: "母婴温馨风格图", prompt: "母婴、温馨、明亮、柔和、浅色系、治愈、可爱", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e6af8de5a9b4.webp" },
  { id: "ecom-e8bf90e58aa8", category: "电商营销", name: "运动健身产品图", prompt: "运动、活力、力量感、冷调、科技感、健身场景", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e8bf90e58aa8.webp" },
  { id: "ecom-e88cb6e9a5ae", category: "电商营销", name: "茶饮饮品主图", prompt: "饮品、清新、明亮、高饱和、食欲感、冰爽、质感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e88cb6e9a5ae.webp" },
  { id: "ecom-e68aa4e882a4", category: "电商营销", name: "护肤产品场景图", prompt: "护肤、高级、水润、质感、干净背景、柔和光线、精致", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e68aa4e882a4.webp" },
  { id: "ecom-e99bb6e9a39f", category: "电商营销", name: "零食小吃主图", prompt: "零食、诱人、高饱和、暖调、食欲、生活化、细节清晰", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e99bb6e9a39f.webp" },
  { id: "ecom-e7aeb1e58c85", category: "电商营销", name: "箱包产品展示图", prompt: "箱包、质感、冷调、简约背景、高级、商业展示、清晰纹理", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e7aeb1e58c85.webp" },
  { id: "ecom-e88a82e697a5", category: "电商营销", name: "节日促销海报", prompt: "促销、喜庆、红色、活动氛围、大字报、商业营销风格", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/ecom-e88a82e697a5.webp" },
  { id: "anime-e4ba8ce6aca1", category: "动漫游戏", name: "二次元少女立绘", prompt: "二次元、少女、大眼睛、日系、精致五官、清新配色、动漫风格", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-e4ba8ce6aca1.webp" },
  { id: "anime-e6b8b8e6888f", category: "动漫游戏", name: "游戏CG角色", prompt: "游戏CG、写实渲染、高精度、光影、3D质感、角色建模", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-e6b8b8e6888f.webp" },
  { id: "anime-51e78988e58d", category: "动漫游戏", name: "Q版卡通角色", prompt: "Q版、卡通、可爱、大头小身、圆润、萌系、简约配色", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-51e78988e58d.webp" },
  { id: "anime-e59bbde9a38e", category: "动漫游戏", name: "国风仙侠角色", prompt: "仙侠、国风、古风、飘逸、仙气、华丽服饰、玄幻氛围", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-e59bbde9a38e.webp" },
  { id: "anime-e8b59be58d9a", category: "动漫游戏", name: "赛博朋克角色", prompt: "赛博朋克、科技、霓虹、未来风、金属、冷色调、科幻", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-e8b59be58d9a.webp" },
  { id: "anime-e697a5e5bc8f", category: "动漫游戏", name: "日式和风角色", prompt: "和风、日式、传统、和服、复古、动漫风格、柔和配色", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-e697a5e5bc8f.webp" },
  { id: "anime-e69a97e9bb91", category: "动漫游戏", name: "暗黑魔幻角色", prompt: "暗黑、魔幻、神秘、冷调、高对比、玄幻、恶魔风格", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-e69a97e9bb91.webp" },
  { id: "anime-e6b2bbe68488", category: "动漫游戏", name: "治愈系动漫插画", prompt: "治愈、清新、柔和、浅色系、动漫插画、温暖氛围", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-e6b2bbe68488.webp" },
  { id: "anime-e69cbae794b2", category: "动漫游戏", name: "机甲科幻角色", prompt: "机甲、科幻、金属、未来、机械感、冷调、高质感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-e69cbae794b2.webp" },
  { id: "anime-e58fa4e9a38e", category: "动漫游戏", name: "古风武侠角色", prompt: "武侠、古风、江湖、帅气、飘逸、国风、玄幻角色", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-e58fa4e9a38e.webp" },
  { id: "anime-e5b091e5a5b3", category: "动漫游戏", name: "少女漫画风格", prompt: "少女漫画、甜美、柔和、粉色系、大眼睛、清新、梦幻", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-e5b091e5a5b3.webp" },
  { id: "anime-e5838fe7b4a0", category: "动漫游戏", name: "像素风游戏角色", prompt: "像素风、复古、8bit、游戏、怀旧、简约配色、经典风格", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-e5838fe7b4a0.webp" },
  { id: "anime-e5b9bbe683b3", category: "动漫游戏", name: "幻想童话角色", prompt: "童话、幻想、梦幻、柔和、治愈、精致、唯美", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-e5b9bbe683b3.webp" },
  { id: "anime-e68898e69697", category: "动漫游戏", name: "战斗风游戏插画", prompt: "战斗、热血、高对比、炫光、动作感、游戏宣传、张力", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-e68898e69697.webp" },
  { id: "anime-e594afe7be8e", category: "动漫游戏", name: "唯美场景插画", prompt: "唯美、场景、动漫、治愈、光影、柔和、幻想世界", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/anime-e594afe7be8e.webp" },
  { id: "illus-e59bbde6bdae", category: "风格插画", name: "国潮国风插画", prompt: "国潮、国风、传统元素、高饱和、红色、现代国潮、平面插画", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e59bbde6bdae.webp" },
  { id: "illus-e6b2bbe68488", category: "风格插画", name: "治愈扁平插画", prompt: "扁平风、简约、治愈、柔和、干净、几何、清新配色", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e6b2bbe68488.webp" },
  { id: "illus-e6b0b4e5bda9", category: "风格插画", name: "水彩手绘插画", prompt: "水彩、手绘、晕染、柔和、清新、艺术、透气质感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e6b0b4e5bda9.webp" },
  { id: "illus-e8828ce79086", category: "风格插画", name: "肌理质感插画", prompt: "肌理、质感、颗粒、艺术、复古、手绘、层次", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e8828ce79086.webp" },
  { id: "illus-e69e81e7ae80", category: "风格插画", name: "极简线条插画", prompt: "极简、线条、简约、黑白、艺术、干净、抽象", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e69e81e7ae80.webp" },
  { id: "illus-e5a48de58fa4", category: "风格插画", name: "复古肌理插画", prompt: "复古、肌理、做旧、暖调、艺术、手绘质感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e5a48de58fa4.webp" },
  { id: "illus-e6a2a6e5b9bb", category: "风格插画", name: "梦幻渐变插画", prompt: "渐变、梦幻、柔和、马卡龙、清新、治愈、唯美", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e6a2a6e5b9bb.webp" },
  { id: "illus-e59586e4b89a", category: "风格插画", name: "商业矢量插画", prompt: "矢量、商业、扁平、简洁、清晰、品牌、推广插画", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e59586e4b89a.webp" },
  { id: "illus-e69a97e9bb91", category: "风格插画", name: "暗黑艺术插画", prompt: "暗黑、艺术、冷调、高对比、神秘、抽象、张力", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e69a97e9bb91.webp" },
  { id: "illus-e697a5e7b3bb", category: "风格插画", name: "日系治愈插画", prompt: "日系、治愈、清新、柔和、浅色系、温暖、生活感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e697a5e7b3bb.webp" },
  { id: "illus-e69687e889ba", category: "风格插画", name: "文艺青年插画", prompt: "文艺、清新、简约、柔和、生活感、温暖、安静", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e69687e889ba.webp" },
  { id: "illus-e584bfe7aba5", category: "风格插画", name: "儿童绘本插画", prompt: "儿童、可爱、明亮、柔和、卡通、治愈、绘本风", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e584bfe7aba5.webp" },
  { id: "illus-e68abde8b1a1", category: "风格插画", name: "抽象艺术插画", prompt: "抽象、艺术、色彩、构成、现代、个性、创意", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e68abde8b1a1.webp" },
  { id: "illus-e59f8ee5b882", category: "风格插画", name: "城市风景插画", prompt: "城市、风景、扁平、简约、清新、治愈、建筑", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e59f8ee5b882.webp" },
  { id: "illus-e887aae784b6", category: "风格插画", name: "自然植物插画", prompt: "植物、自然、清新、治愈、扁平、手绘、柔和", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/illus-e887aae784b6.webp" },
  { id: "graphic-e69e81e7ae80", category: "平面设计", name: "极简海报设计", prompt: "极简、留白、高级、冷调、文字排版、简约海报", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e69e81e7ae80.webp" },
  { id: "graphic-e59bbde6bdae", category: "平面设计", name: "国潮品牌视觉", prompt: "国潮、品牌、红色、传统元素、现代视觉、大气", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e59bbde6bdae.webp" },
  { id: "graphic-e69687e889ba", category: "平面设计", name: "文艺画册版式", prompt: "文艺、版式、清新、柔和、画册、干净、高级", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e69687e889ba.webp" },
  { id: "graphic-e7a791e68a80", category: "平面设计", name: "科技风视觉", prompt: "科技、未来、线条、冷调、光效、现代、视觉冲击", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e7a791e68a80.webp" },
  { id: "graphic-e5a48de58fa4", category: "平面设计", name: "复古海报设计", prompt: "复古、做旧、暖调、肌理、大字报、艺术、怀旧", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e5a48de58fa4.webp" },
  { id: "graphic-e6b885e696b0", category: "平面设计", name: "清新文创视觉", prompt: "清新、文创、柔和、治愈、简约、文艺、干净", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e6b885e696b0.webp" },
  { id: "graphic-e8bdbbe5a5a2", category: "平面设计", name: "轻奢品牌设计", prompt: "轻奢、高级、冷金、质感、简约、品牌、精致", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e8bdbbe5a5a2.webp" },
  { id: "graphic-e6bdaee6b581", category: "平面设计", name: "潮流街头视觉", prompt: "街头、潮流、高饱和、个性、年轻、涂鸦、现代", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e6bdaee6b581.webp" },
  { id: "graphic-e697a5e5bc8f", category: "平面设计", name: "日式简约排版", prompt: "日式、简约、留白、文字排版、清新、高级、安静", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e697a5e5bc8f.webp" },
  { id: "graphic-e59586e58aa1", category: "平面设计", name: "商务办公视觉", prompt: "商务、简约、蓝色、专业、干净、办公、品牌", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e59586e58aa1.webp" },
  { id: "graphic-e889bae69caf", category: "平面设计", name: "艺术展览海报", prompt: "艺术、展览、抽象、高级、排版、创意、视觉", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e889bae69caf.webp" },
  { id: "graphic-e88a82e697a5", category: "平面设计", name: "节日活动视觉", prompt: "节日、活动、喜庆、红色、氛围、商业、宣传", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e88a82e697a5.webp" },
  { id: "graphic-e9a490e9a5ae", category: "平面设计", name: "餐饮品牌视觉", prompt: "餐饮、美食、暖调、食欲、品牌、简约、质感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e9a490e9a5ae.webp" },
  { id: "graphic-e7be8ee5a686", category: "平面设计", name: "美妆品牌视觉", prompt: "美妆、高级、清新、质感、精致、品牌、柔和", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e7be8ee5a686.webp" },
  { id: "graphic-e59f8ee5b882", category: "平面设计", name: "城市文创设计", prompt: "城市、文创、国风、简约、质感、纪念、艺术", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/graphic-e59f8ee5b882.webp" },
  { id: "arch-e78eb0e4bba3", category: "建筑及室内设计", name: "现代简约客厅", prompt: "现代简约、客厅、明亮、原木、白灰、高级、干净", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e78eb0e4bba3.webp" },
  { id: "arch-e58c97e6aca7", category: "建筑及室内设计", name: "北欧风卧室", prompt: "北欧、卧室、清新、浅色系、温馨、原木、简约", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e58c97e6aca7.webp" },
  { id: "arch-e696b0e4b8ad", category: "建筑及室内设计", name: "新中式茶室", prompt: "新中式、茶室、国风、原木、禅意、安静、典雅", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e696b0e4b8ad.webp" },
  { id: "arch-e8bdbbe5a5a2", category: "建筑及室内设计", name: "轻奢风餐厅", prompt: "轻奢、餐厅、金属、质感、暖光、高级、精致", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e8bdbbe5a5a2.webp" },
  { id: "arch-e5b7a5e4b89a", category: "建筑及室内设计", name: "工业风空间", prompt: "工业风、水泥、冷调、复古、金属、粗犷、个性", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e5b7a5e4b89a.webp" },
  { id: "arch-e697a5e5bc8f", category: "建筑及室内设计", name: "日式禅意空间", prompt: "日式、禅意、原木、榻榻米、简约、安静、治愈", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e697a5e5bc8f.webp" },
  { id: "arch-e78eb0e4bba3-2", category: "建筑及室内设计", name: "现代办公空间", prompt: "办公、现代、简约、明亮、专业、干净、大气", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e78eb0e4bba3-2.webp" },
  { id: "arch-e6b395e5bc8f", category: "建筑及室内设计", name: "法式复古空间", prompt: "法式、复古、线条、暖调、优雅、精致、温馨", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e6b395e5bc8f.webp" },
  { id: "arch-e69e81e7ae80", category: "建筑及室内设计", name: "极简卫生间", prompt: "极简、卫生间、白灰、质感、干净、高级、明亮", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e69e81e7ae80.webp" },
  { id: "arch-e4be98e5af82", category: "建筑及室内设计", name: "侘寂风空间", prompt: "侘寂、水泥、肌理、质朴、自然、禅意、艺术", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e4be98e5af82.webp" },
  { id: "arch-e78eb0e4bba3-3", category: "建筑及室内设计", name: "现代儿童房", prompt: "儿童房、明亮、清新、温馨、简约、安全、可爱", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e78eb0e4bba3-3.webp" },
  { id: "arch-e9ab98e7abaf", category: "建筑及室内设计", name: "高端酒店大堂", prompt: "酒店、高端、大气、轻奢、明亮、高级、质感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e9ab98e7abaf.webp" },
  { id: "arch-e78eb0e4bba3-4", category: "建筑及室内设计", name: "现代别墅外观", prompt: "别墅、现代、外观、大气、简约、线条、高级", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e78eb0e4bba3-4.webp" },
  { id: "arch-e69a96e889b2", category: "建筑及室内设计", name: "暖色系居家空间", prompt: "暖色系、居家、温馨、治愈、明亮、简约、舒适", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e69a96e889b2.webp" },
  { id: "arch-e59586e4b89a", category: "建筑及室内设计", name: "商业店铺空间", prompt: "商业、店铺、现代、明亮、简约、高级、质感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/arch-e59586e4b89a.webp" },
  { id: "creative-e8b59be58d9a", category: "创意玩法", name: "赛博朋克合成", prompt: "赛博朋克、霓虹、科幻、未来、冷调、光影、创意合成", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e8b59be58d9a.webp" },
  { id: "creative-e58f8ce9878d", category: "创意玩法", name: "双重曝光艺术", prompt: "双重曝光、人像、风景、融合、艺术、意境、创意", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e58f8ce9878d.webp" },
  { id: "creative-e892b8e6b1bd", category: "创意玩法", name: "蒸汽波风格", prompt: "蒸汽波、复古、粉紫、高饱和、迷幻、怀旧、创意", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e892b8e6b1bd.webp" },
  { id: "creative-e69585e99a9c", category: "创意玩法", name: "故障艺术风", prompt: "故障风、失真、条纹、科技、未来、个性、视觉冲击", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e69585e99a9c.webp" },
  { id: "creative-e58589e5bdb1", category: "创意玩法", name: "光影涂鸦效果", prompt: "光影、涂鸦、光绘、夜景、创意、艺术、氛围", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e58589e5bdb1.webp" },
  { id: "creative-e68bbce8b4b4", category: "创意玩法", name: "拼贴艺术风格", prompt: "拼贴、复古、艺术、个性、混搭、创意、视觉", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e68bbce8b4b4.webp" },
  { id: "creative-e6a2a6e5b9bb", category: "创意玩法", name: "梦幻虚化光影", prompt: "梦幻、虚化、光斑、柔光、治愈、清新、创意", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e6a2a6e5b9bb.webp" },
  { id: "creative-e6b0b4e5a2a8", category: "创意玩法", name: "水墨融结合成", prompt: "水墨、国风、融合、意境、艺术、创意、古典", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e6b0b4e5a2a8.webp" },
  { id: "creative-e69caae69da5", category: "创意玩法", name: "未来科技合成", prompt: "科技、未来、光效、冷调、科幻、创意、视觉", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e69caae69da5.webp" },
  { id: "creative-e5a48de58fa4", category: "创意玩法", name: "复古胶片特效", prompt: "胶片、复古、颗粒、做旧、暖调、文艺、创意", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e5a48de58fa4.webp" },
  { id: "creative-e6898be7bb98", category: "创意玩法", name: "手绘涂鸦风格", prompt: "涂鸦、手绘、街头、个性、高饱和、创意、艺术", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e6898be7bb98.webp" },
  { id: "creative-e69e81e7ae80", category: "创意玩法", name: "极简负感效果", prompt: "负感、极简、黑白、艺术、创意、视觉、高级", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e69e81e7ae80.webp" },
  { id: "creative-e887aae784b6", category: "创意玩法", name: "自然融结合成", prompt: "自然、融合、人像、风景、治愈、创意、意境", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e887aae784b6.webp" },
  { id: "creative-e99c93e899b9", category: "创意玩法", name: "霓虹光效人像", prompt: "霓虹、光效、人像、夜景、赛博、创意、氛围", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e99c93e899b9.webp" },
  { id: "creative-e68abde8b1a1", category: "创意玩法", name: "抽象色彩艺术", prompt: "抽象、色彩、艺术、创意、视觉、个性、构成", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/creative-e68abde8b1a1.webp" },
  { id: "cultural-e58fa4e9a38e", category: "文创周边", name: "古风书签设计", prompt: "古风、书签、国风、典雅、简约、质感、文创", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e58fa4e9a38e.webp" },
  { id: "cultural-e58fafe788b1", category: "文创周边", name: "可爱手账贴纸", prompt: "可爱、手账、贴纸、清新、治愈、卡通、文创", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e58fafe788b1.webp" },
  { id: "cultural-e59bbde6bdae", category: "文创周边", name: "国潮帆布包", prompt: "国潮、帆布包、国风、红色、质感、文创、潮流", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e59bbde6bdae.webp" },
  { id: "cultural-e69687e889ba", category: "文创周边", name: "文艺笔记本", prompt: "文艺、笔记本、清新、简约、质感、文创、治愈", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e69687e889ba.webp" },
  { id: "cultural-e58fa4e9a38e-2", category: "文创周边", name: "古风团扇设计", prompt: "古风、团扇、国风、典雅、意境、文创、艺术", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e58fa4e9a38e-2.webp" },
  { id: "cultural-e58da1e9809a", category: "文创周边", name: "卡通徽章设计", prompt: "卡通、徽章、可爱、清新、文创、质感、小巧", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e58da1e9809a.webp" },
  { id: "cultural-e59f8ee5b882", category: "文创周边", name: "城市纪念明信片", prompt: "城市、明信片、纪念、国风、简约、文创、艺术", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e59f8ee5b882.webp" },
  { id: "cultural-e6b2bbe68488", category: "文创周边", name: "治愈系手机壳", prompt: "治愈、手机壳、清新、简约、文创、质感、可爱", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e6b2bbe68488.webp" },
  { id: "cultural-e7a685e6848f", category: "文创周边", name: "禅意茶具文创", prompt: "禅意、茶具、国风、质朴、质感、文创、典雅", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e7a685e6848f.webp" },
  { id: "cultural-e69687e889ba-2", category: "文创周边", name: "文艺帆布袋", prompt: "文艺、帆布袋、清新、简约、质感、文创、日常", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e69687e889ba-2.webp" },
  { id: "cultural-e58fa4e9a38e-3", category: "文创周边", name: "古风发簪设计", prompt: "古风、发簪、国风、典雅、精致、文创、传统", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e58fa4e9a38e-3.webp" },
  { id: "cultural-e58fafe788b1-2", category: "文创周边", name: "可爱玩偶文创", prompt: "可爱、玩偶、治愈、清新、文创、质感、萌系", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e58fafe788b1-2.webp" },
  { id: "cultural-e7ae80e7baa6", category: "文创周边", name: "简约香薰包装", prompt: "简约、香薰、包装、清新、质感、文创、高级", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e7ae80e7baa6.webp" },
  { id: "cultural-e59bbde9a38e", category: "文创周边", name: "国风纸胶带", prompt: "国风、纸胶带、复古、文艺、文创、手账、质感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e59bbde9a38e.webp" },
  { id: "cultural-e889bae69caf", category: "文创周边", name: "艺术装饰版画", prompt: "艺术、版画、装饰、简约、文艺、文创、高级", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/cultural-e889bae69caf.webp" },
  { id: "novel-e58fa4e9a38e", category: "小说推文", name: "古风言情推文", prompt: "古风、言情、唯美、意境、古典、温柔、小说推文", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e58fa4e9a38e.webp" },
  { id: "novel-e983bde5b882", category: "小说推文", name: "都市甜宠推文", prompt: "都市、甜宠、清新、明亮、治愈、温暖、小说推文", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e983bde5b882.webp" },
  { id: "novel-e78e84e5b9bb", category: "小说推文", name: "玄幻修仙推文", prompt: "玄幻、修仙、霸气、光影、国风、小说推文、张力", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e78e84e5b9bb.webp" },
  { id: "novel-e682ace79691", category: "小说推文", name: "悬疑推理推文", prompt: "悬疑、推理、暗调、神秘、冷调、小说推文、氛围", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e682ace79691.webp" },
  { id: "novel-e6a0a1e59bad", category: "小说推文", name: "校园青春推文", prompt: "校园、青春、清新、明亮、治愈、少年感、小说推文", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e6a0a1e59bad.webp" },
  { id: "novel-e99cb8e98193", category: "小说推文", name: "霸道总裁推文", prompt: "总裁、都市、冷调、高级、质感、小说推文、霸气", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e99cb8e98193.webp" },
  { id: "novel-e7a9bfe8b68a", category: "小说推文", name: "穿越重生推文", prompt: "穿越、重生、古风、玄幻、意境、小说推文、视觉", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e7a9bfe8b68a.webp" },
  { id: "novel-e880bde7be8e", category: "小说推文", name: "耽美纯爱推文", prompt: "纯爱、文艺、清新、柔和、治愈、小说推文、氛围", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e880bde7be8e.webp" },
  { id: "novel-e69cabe4b896", category: "小说推文", name: "末世科幻推文", prompt: "末世、科幻、废土、冷调、未来、小说推文、视觉", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e69cabe4b896.webp" },
  { id: "novel-e58fa4e4bba3", category: "小说推文", name: "古代权谋推文", prompt: "权谋、古风、大气、暗调、意境、小说推文、张力", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e58fa4e4bba3.webp" },
  { id: "novel-e8bdbbe69dbe", category: "小说推文", name: "轻松搞笑推文", prompt: "搞笑、轻松、明亮、清新、治愈、小说推文、可爱", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e8bdbbe69dbe.webp" },
  { id: "novel-e794b5e7ab9e", category: "小说推文", name: "电竞甜文推文", prompt: "电竞、都市、青春、冷调、科技、小说推文、活力", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e794b5e7ab9e.webp" },
  { id: "novel-e4bb99e4bea0", category: "小说推文", name: "仙侠虐恋推文", prompt: "仙侠、虐恋、古风、唯美、意境、小说推文、悲伤", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e4bb99e4bea0.webp" },
  { id: "novel-e58e86e58fb2", category: "小说推文", name: "历史正剧推文", prompt: "历史、正剧、古风、大气、典雅、小说推文、质感", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e58e86e58fb2.webp" },
  { id: "novel-e5a8b1e4b990", category: "小说推文", name: "娱乐圈文推文", prompt: "娱乐圈、都市、时尚、明亮、高级、小说推文、氛围", imageUrl: "https://tool-mall.oss-cn-guangzhou.aliyuncs.com/canvas/style-library/novel-e5a8b1e4b990.webp" },
];
